version: "3.3"
services:
  graphql:
    restart: always
    container_name: graphql
    image: node:latest
    restart: always
    working_dir: /home/node/app
    volumes:
     - ./graphql-server:/home/node/app
     - /home/node/app/node_modules
    command: /bin/bash "start.sh"
    links:
     - mongo:mongodb
    ports:
     - "4000:4000"
     - 3000:3000
     - "9229:9229"
    env_file:
     - .env

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
     - db-data:/data/db
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}

volumes:
  db-data:
